baseURL = "/"
languageCode = "en"
defaultContentLanguage = "en"
title = "scrollodex"
#theme = "bizone"
paginate = 10
timeout = 200000

[params]
lazyload = 1
debug = 1
wysiwyg = 0
branding = 1

[taxonomies]
	category = "categories"
	country = "countries"
	region = "regions"

[markup]
	[markup.tableOfContents]
		endLevel = 3
		ordered = false
		startLevel = 2
	[markup.goldmark.renderer]
		unsafe= true

[module]
[[module.mounts]]
# Workaround for https://github.com/gohugoio/hugo/issues/6945
source = "assets/scss/bootstrap/_vendor"
target = "assets/scss/bootstrap/vendor"
[[module.mounts]]
source = "assets/js"
target = "assets/js"

[[module.imports]]
path = "github.com/twbs/bootstrap"
disable = false
ignoreConfig = true
ignoreImports = true
[[module.imports.mounts]]
source = "scss"
target = "assets/scss/bootstrap"
[[module.imports.mounts]]
source = "js"
target = "assets/js/bootstrap"
